// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BrokerFlowNode represents an individual Kafka broker and its hosted partitions
 */
export class BrokerFlowNode {
    "nodeId": number;
    "host": string;
    "port": number;
    "isController": boolean;
    "rack"?: string;
    "partitions": PartitionFlowNode[];

    /**
     * MB/s across this broker
     */
    "throughputMb": number;

    /**
     * msg/s across this broker
     */
    "msgRate": number;

    /** Creates a new BrokerFlowNode instance. */
    constructor($$source: Partial<BrokerFlowNode> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("isController" in $$source)) {
            this["isController"] = false;
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = [];
        }
        if (!("throughputMb" in $$source)) {
            this["throughputMb"] = 0;
        }
        if (!("msgRate" in $$source)) {
            this["msgRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerFlowNode instance from a string or object.
     */
    static createFrom($$source: any = {}): BrokerFlowNode {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("partitions" in $$parsedSource) {
            $$parsedSource["partitions"] = $$createField5_0($$parsedSource["partitions"]);
        }
        return new BrokerFlowNode($$parsedSource as Partial<BrokerFlowNode>);
    }
}

/**
 * ClusterFlowData encapsulates the entire end-to-end live pipeline topology
 */
export class ClusterFlowData {
    "topic": string;
    "clusterId": string;
    "controllerId": number;
    "brokers": BrokerFlowNode[];
    "totalPartitions": number;
    "totalMessages": number;
    "producer": StressTestMetrics;
    "consumer": ConsumerBenchmarkMetrics;

    /** Creates a new ClusterFlowData instance. */
    constructor($$source: Partial<ClusterFlowData> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("clusterId" in $$source)) {
            this["clusterId"] = "";
        }
        if (!("controllerId" in $$source)) {
            this["controllerId"] = 0;
        }
        if (!("brokers" in $$source)) {
            this["brokers"] = [];
        }
        if (!("totalPartitions" in $$source)) {
            this["totalPartitions"] = 0;
        }
        if (!("totalMessages" in $$source)) {
            this["totalMessages"] = 0;
        }
        if (!("producer" in $$source)) {
            this["producer"] = (new StressTestMetrics());
        }
        if (!("consumer" in $$source)) {
            this["consumer"] = (new ConsumerBenchmarkMetrics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterFlowData instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterFlowData {
        const $$createField3_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("brokers" in $$parsedSource) {
            $$parsedSource["brokers"] = $$createField3_0($$parsedSource["brokers"]);
        }
        if ("producer" in $$parsedSource) {
            $$parsedSource["producer"] = $$createField6_0($$parsedSource["producer"]);
        }
        if ("consumer" in $$parsedSource) {
            $$parsedSource["consumer"] = $$createField7_0($$parsedSource["consumer"]);
        }
        return new ClusterFlowData($$parsedSource as Partial<ClusterFlowData>);
    }
}

export class ConnectionConfig {
    "id": string;
    "name": string;
    "brokers": string[];

    /**
     * "none", "plain", "scram-sha-256", "scram-sha-512", "ssl", "mtls", "oauthbearer"
     */
    "authType": string;
    "username": string;
    "password": string;
    "tlsEnabled": boolean;
    "caCertPath": string;
    "clientCertPath": string;
    "clientKeyPath": string;
    "insecureSkipVerify": boolean;
    "token": string;
    "schemaRegistryUrl": string;
    "schemaRegistryUser": string;
    "schemaRegistryPass": string;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("brokers" in $$source)) {
            this["brokers"] = [];
        }
        if (!("authType" in $$source)) {
            this["authType"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("tlsEnabled" in $$source)) {
            this["tlsEnabled"] = false;
        }
        if (!("caCertPath" in $$source)) {
            this["caCertPath"] = "";
        }
        if (!("clientCertPath" in $$source)) {
            this["clientCertPath"] = "";
        }
        if (!("clientKeyPath" in $$source)) {
            this["clientKeyPath"] = "";
        }
        if (!("insecureSkipVerify" in $$source)) {
            this["insecureSkipVerify"] = false;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("schemaRegistryUrl" in $$source)) {
            this["schemaRegistryUrl"] = "";
        }
        if (!("schemaRegistryUser" in $$source)) {
            this["schemaRegistryUser"] = "";
        }
        if (!("schemaRegistryPass" in $$source)) {
            this["schemaRegistryPass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("brokers" in $$parsedSource) {
            $$parsedSource["brokers"] = $$createField2_0($$parsedSource["brokers"]);
        }
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

export class ConnectionStatus {
    "connected": boolean;
    "clusterId": string;
    "controllerId": number;
    "brokers": string[];
    "topicsCount": number;
    "latencyMs": number;
    "error"?: string;

    /** Creates a new ConnectionStatus instance. */
    constructor($$source: Partial<ConnectionStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("clusterId" in $$source)) {
            this["clusterId"] = "";
        }
        if (!("controllerId" in $$source)) {
            this["controllerId"] = 0;
        }
        if (!("brokers" in $$source)) {
            this["brokers"] = [];
        }
        if (!("topicsCount" in $$source)) {
            this["topicsCount"] = 0;
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStatus {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("brokers" in $$parsedSource) {
            $$parsedSource["brokers"] = $$createField3_0($$parsedSource["brokers"]);
        }
        return new ConnectionStatus($$parsedSource as Partial<ConnectionStatus>);
    }
}

export class ConsumerBenchmarkConfig {
    "topic": string;
    "groupId": string;

    /**
     * "drop", "store", "inspect"
     */
    "mode": string;
    "storeFilePath": string;

    /**
     * "raw", "jsonl", "csv_hex", "pcap_like"
     */
    "storeFormat": string;

    /**
     * "latest", "earliest"
     */
    "autoOffsetReset": string;
    "kaitaiFormatId"?: string;

    /** Creates a new ConsumerBenchmarkConfig instance. */
    constructor($$source: Partial<ConsumerBenchmarkConfig> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("storeFilePath" in $$source)) {
            this["storeFilePath"] = "";
        }
        if (!("storeFormat" in $$source)) {
            this["storeFormat"] = "";
        }
        if (!("autoOffsetReset" in $$source)) {
            this["autoOffsetReset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerBenchmarkConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerBenchmarkConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumerBenchmarkConfig($$parsedSource as Partial<ConsumerBenchmarkConfig>);
    }
}

export class ConsumerBenchmarkMetrics {
    "active": boolean;
    "topic": string;
    "mode": string;
    "elapsedSeconds": number;
    "consumedMessages": number;
    "consumedBytes": number;
    "currentMsgRate": number;
    "currentByteRate": number;
    "droppedMessages": number;
    "storedMessages": number;
    "errorsCount": number;

    /** Creates a new ConsumerBenchmarkMetrics instance. */
    constructor($$source: Partial<ConsumerBenchmarkMetrics> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("elapsedSeconds" in $$source)) {
            this["elapsedSeconds"] = 0;
        }
        if (!("consumedMessages" in $$source)) {
            this["consumedMessages"] = 0;
        }
        if (!("consumedBytes" in $$source)) {
            this["consumedBytes"] = 0;
        }
        if (!("currentMsgRate" in $$source)) {
            this["currentMsgRate"] = 0;
        }
        if (!("currentByteRate" in $$source)) {
            this["currentByteRate"] = 0;
        }
        if (!("droppedMessages" in $$source)) {
            this["droppedMessages"] = 0;
        }
        if (!("storedMessages" in $$source)) {
            this["storedMessages"] = 0;
        }
        if (!("errorsCount" in $$source)) {
            this["errorsCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerBenchmarkMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerBenchmarkMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumerBenchmarkMetrics($$parsedSource as Partial<ConsumerBenchmarkMetrics>);
    }
}

export class ConsumerGroupInfo {
    "groupId": string;
    "state": string;
    "protocolType": string;
    "protocol": string;
    "members": ConsumerGroupMember[];
    "lagTotal": number;

    /** Creates a new ConsumerGroupInfo instance. */
    constructor($$source: Partial<ConsumerGroupInfo> = {}) {
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("protocolType" in $$source)) {
            this["protocolType"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("members" in $$source)) {
            this["members"] = [];
        }
        if (!("lagTotal" in $$source)) {
            this["lagTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerGroupInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerGroupInfo {
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField4_0($$parsedSource["members"]);
        }
        return new ConsumerGroupInfo($$parsedSource as Partial<ConsumerGroupInfo>);
    }
}

export class ConsumerGroupMember {
    "memberId": string;
    "clientId": string;
    "clientHost": string;

    /** Creates a new ConsumerGroupMember instance. */
    constructor($$source: Partial<ConsumerGroupMember> = {}) {
        if (!("memberId" in $$source)) {
            this["memberId"] = "";
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("clientHost" in $$source)) {
            this["clientHost"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerGroupMember instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerGroupMember {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumerGroupMember($$parsedSource as Partial<ConsumerGroupMember>);
    }
}

export class CreateTopicRequest {
    "name": string;
    "partitions": number;
    "replicationFactor": number;

    /**
     * e.g. "retention.ms": "86400000", "cleanup.policy": "delete"
     */
    "configs": { [_ in string]?: string };

    /** Creates a new CreateTopicRequest instance. */
    constructor($$source: Partial<CreateTopicRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = 0;
        }
        if (!("replicationFactor" in $$source)) {
            this["replicationFactor"] = 0;
        }
        if (!("configs" in $$source)) {
            this["configs"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTopicRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTopicRequest {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField3_0($$parsedSource["configs"]);
        }
        return new CreateTopicRequest($$parsedSource as Partial<CreateTopicRequest>);
    }
}

export class KafkaRecord {
    "topic": string;
    "partition": number;
    "offset": number;
    "key": string;
    "keyBase64": string;
    "value": string;
    "valueBase64": string;
    "valueHex": string;
    "headers": { [_ in string]?: string };
    "timestamp": string;

    /**
     * "json", "binary", "text", "avro", "protobuf"
     */
    "format": string;

    /**
     * Populated if parsed via Kaitai or Schema Registry
     */
    "parsedJson": string;

    /** Creates a new KafkaRecord instance. */
    constructor($$source: Partial<KafkaRecord> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("partition" in $$source)) {
            this["partition"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("keyBase64" in $$source)) {
            this["keyBase64"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("valueBase64" in $$source)) {
            this["valueBase64"] = "";
        }
        if (!("valueHex" in $$source)) {
            this["valueHex"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("parsedJson" in $$source)) {
            this["parsedJson"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KafkaRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): KafkaRecord {
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField8_0($$parsedSource["headers"]);
        }
        return new KafkaRecord($$parsedSource as Partial<KafkaRecord>);
    }
}

export class KaitaiFormat {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "extension": string;
    "ksySrc": string;
    "compiled": boolean;
    "binaryPath": string;
    "lastBuilt": string;
    "structName": string;
    "checksum": string;
    "buildError"?: string;

    /** Creates a new KaitaiFormat instance. */
    constructor($$source: Partial<KaitaiFormat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("ksySrc" in $$source)) {
            this["ksySrc"] = "";
        }
        if (!("compiled" in $$source)) {
            this["compiled"] = false;
        }
        if (!("binaryPath" in $$source)) {
            this["binaryPath"] = "";
        }
        if (!("lastBuilt" in $$source)) {
            this["lastBuilt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("structName" in $$source)) {
            this["structName"] = "";
        }
        if (!("checksum" in $$source)) {
            this["checksum"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KaitaiFormat instance from a string or object.
     */
    static createFrom($$source: any = {}): KaitaiFormat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KaitaiFormat($$parsedSource as Partial<KaitaiFormat>);
    }
}

export class ParseRequest {
    "formatId": string;
    "dataBase64": string;
    "dataHex": string;

    /** Creates a new ParseRequest instance. */
    constructor($$source: Partial<ParseRequest> = {}) {
        if (!("formatId" in $$source)) {
            this["formatId"] = "";
        }
        if (!("dataBase64" in $$source)) {
            this["dataBase64"] = "";
        }
        if (!("dataHex" in $$source)) {
            this["dataHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ParseRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParseRequest($$parsedSource as Partial<ParseRequest>);
    }
}

export class ParseResult {
    "success": boolean;
    "error"?: string;
    "result"?: any;
    "elapsedMs": number;

    /** Creates a new ParseResult instance. */
    constructor($$source: Partial<ParseResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ParseResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParseResult($$parsedSource as Partial<ParseResult>);
    }
}

/**
 * PartitionFlowNode represents partition state and traffic metrics
 */
export class PartitionFlowNode {
    "id": number;
    "leader": number;
    "replicas": number[];
    "isr": number[];
    "highWatermark": number;

    /**
     * estimated or calculated msg/s
     */
    "produceRate": number;

    /**
     * MB/s
     */
    "throughputMbps": number;

    /** Creates a new PartitionFlowNode instance. */
    constructor($$source: Partial<PartitionFlowNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("leader" in $$source)) {
            this["leader"] = 0;
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = [];
        }
        if (!("isr" in $$source)) {
            this["isr"] = [];
        }
        if (!("highWatermark" in $$source)) {
            this["highWatermark"] = 0;
        }
        if (!("produceRate" in $$source)) {
            this["produceRate"] = 0;
        }
        if (!("throughputMbps" in $$source)) {
            this["throughputMbps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PartitionFlowNode instance from a string or object.
     */
    static createFrom($$source: any = {}): PartitionFlowNode {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("replicas" in $$parsedSource) {
            $$parsedSource["replicas"] = $$createField2_0($$parsedSource["replicas"]);
        }
        if ("isr" in $$parsedSource) {
            $$parsedSource["isr"] = $$createField3_0($$parsedSource["isr"]);
        }
        return new PartitionFlowNode($$parsedSource as Partial<PartitionFlowNode>);
    }
}

export class PartitionInfo {
    "id": number;
    "leader": number;
    "replicas": number[];
    "isr": number[];
    "earliestOffset": number;
    "latestOffset": number;

    /** Creates a new PartitionInfo instance. */
    constructor($$source: Partial<PartitionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("leader" in $$source)) {
            this["leader"] = 0;
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = [];
        }
        if (!("isr" in $$source)) {
            this["isr"] = [];
        }
        if (!("earliestOffset" in $$source)) {
            this["earliestOffset"] = 0;
        }
        if (!("latestOffset" in $$source)) {
            this["latestOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PartitionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PartitionInfo {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("replicas" in $$parsedSource) {
            $$parsedSource["replicas"] = $$createField2_0($$parsedSource["replicas"]);
        }
        if ("isr" in $$parsedSource) {
            $$parsedSource["isr"] = $$createField3_0($$parsedSource["isr"]);
        }
        return new PartitionInfo($$parsedSource as Partial<PartitionInfo>);
    }
}

export class ProduceRequest {
    "topic": string;
    "key": string;

    /**
     * "string", "hex", "base64"
     */
    "keyFormat": string;
    "value": string;

    /**
     * "string", "json", "base64", "hex", "binary"
     */
    "valueFormat": string;
    "headers": { [_ in string]?: string };

    /**
     * -1 for auto-hash/round-robin
     */
    "partition": number;
    "kaitaiFormatId"?: string;

    /** Creates a new ProduceRequest instance. */
    constructor($$source: Partial<ProduceRequest> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("keyFormat" in $$source)) {
            this["keyFormat"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("valueFormat" in $$source)) {
            this["valueFormat"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("partition" in $$source)) {
            this["partition"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProduceRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProduceRequest {
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField5_0($$parsedSource["headers"]);
        }
        return new ProduceRequest($$parsedSource as Partial<ProduceRequest>);
    }
}

export class ProduceResponse {
    "success": boolean;
    "topic": string;
    "partition": number;
    "offset": number;
    "timestamp": string;
    "error"?: string;

    /** Creates a new ProduceResponse instance. */
    constructor($$source: Partial<ProduceResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("partition" in $$source)) {
            this["partition"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProduceResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ProduceResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProduceResponse($$parsedSource as Partial<ProduceResponse>);
    }
}

export class StressTestConfig {
    "topic": string;

    /**
     * goroutine worker pool count
     */
    "concurrency": number;

    /**
     * messages/second across all workers (0 for unbounded max speed)
     */
    "targetRate": number;

    /**
     * 0 for until stopped
     */
    "durationSeconds": number;

    /**
     * size for random payload
     */
    "messageSizeBytes": number;

    /**
     * "random", "counter", "custom", "kaitai_template"
     */
    "payloadType": string;

    /**
     * Used if payloadType == "custom"
     */
    "customPayload": string;

    /**
     * Used if payloadType == "kaitai_template"
     */
    "kaitaiFormatId": string;

    /**
     * "none", "uuid", "counter", "fixed"
     */
    "keyPattern": string;

    /**
     * "none", "gzip", "snappy", "lz4", "zstd"
     */
    "compression": string;

    /** Creates a new StressTestConfig instance. */
    constructor($$source: Partial<StressTestConfig> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("targetRate" in $$source)) {
            this["targetRate"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            this["durationSeconds"] = 0;
        }
        if (!("messageSizeBytes" in $$source)) {
            this["messageSizeBytes"] = 0;
        }
        if (!("payloadType" in $$source)) {
            this["payloadType"] = "";
        }
        if (!("customPayload" in $$source)) {
            this["customPayload"] = "";
        }
        if (!("kaitaiFormatId" in $$source)) {
            this["kaitaiFormatId"] = "";
        }
        if (!("keyPattern" in $$source)) {
            this["keyPattern"] = "";
        }
        if (!("compression" in $$source)) {
            this["compression"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StressTestConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): StressTestConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StressTestConfig($$parsedSource as Partial<StressTestConfig>);
    }
}

export class StressTestMetrics {
    "active": boolean;
    "topic": string;
    "elapsedSeconds": number;
    "sentMessages": number;
    "sentBytes": number;
    "currentMsgRate": number;
    "currentByteRate": number;
    "errorsCount": number;
    "lastError"?: string;

    /**
     * ms
     */
    "latencyP50": number;

    /**
     * ms
     */
    "latencyP95": number;

    /**
     * ms
     */
    "latencyP99": number;

    /**
     * ms
     */
    "latencyAvg": number;

    /** Creates a new StressTestMetrics instance. */
    constructor($$source: Partial<StressTestMetrics> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("elapsedSeconds" in $$source)) {
            this["elapsedSeconds"] = 0;
        }
        if (!("sentMessages" in $$source)) {
            this["sentMessages"] = 0;
        }
        if (!("sentBytes" in $$source)) {
            this["sentBytes"] = 0;
        }
        if (!("currentMsgRate" in $$source)) {
            this["currentMsgRate"] = 0;
        }
        if (!("currentByteRate" in $$source)) {
            this["currentByteRate"] = 0;
        }
        if (!("errorsCount" in $$source)) {
            this["errorsCount"] = 0;
        }
        if (!("latencyP50" in $$source)) {
            this["latencyP50"] = 0;
        }
        if (!("latencyP95" in $$source)) {
            this["latencyP95"] = 0;
        }
        if (!("latencyP99" in $$source)) {
            this["latencyP99"] = 0;
        }
        if (!("latencyAvg" in $$source)) {
            this["latencyAvg"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StressTestMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): StressTestMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StressTestMetrics($$parsedSource as Partial<StressTestMetrics>);
    }
}

export class TailRequest {
    "topic": string;

    /**
     * -1 for all partitions
     */
    "partition": number;

    /**
     * e.g. last 10, 50, 100 messages
     */
    "count": number;
    "kaitaiFormatId"?: string;

    /** Creates a new TailRequest instance. */
    constructor($$source: Partial<TailRequest> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("partition" in $$source)) {
            this["partition"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TailRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TailRequest($$parsedSource as Partial<TailRequest>);
    }
}

export class TopicConfigEntry {
    "name": string;
    "value": string;
    "isDefault": boolean;
    "source": string;

    /** Creates a new TopicConfigEntry instance. */
    constructor($$source: Partial<TopicConfigEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicConfigEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicConfigEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicConfigEntry($$parsedSource as Partial<TopicConfigEntry>);
    }
}

export class TopicDetail {
    "name": string;
    "partitionsCount": number;
    "replicationFactor": number;
    "partitions": PartitionInfo[];
    "configs": TopicConfigEntry[];

    /** Creates a new TopicDetail instance. */
    constructor($$source: Partial<TopicDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("partitionsCount" in $$source)) {
            this["partitionsCount"] = 0;
        }
        if (!("replicationFactor" in $$source)) {
            this["replicationFactor"] = 0;
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = [];
        }
        if (!("configs" in $$source)) {
            this["configs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicDetail {
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("partitions" in $$parsedSource) {
            $$parsedSource["partitions"] = $$createField3_0($$parsedSource["partitions"]);
        }
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField4_0($$parsedSource["configs"]);
        }
        return new TopicDetail($$parsedSource as Partial<TopicDetail>);
    }
}

export class TopicSummary {
    "name": string;
    "partitionsCount": number;
    "replicationFactor": number;
    "partitions": PartitionInfo[];

    /** Creates a new TopicSummary instance. */
    constructor($$source: Partial<TopicSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("partitionsCount" in $$source)) {
            this["partitionsCount"] = 0;
        }
        if (!("replicationFactor" in $$source)) {
            this["replicationFactor"] = 0;
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicSummary {
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("partitions" in $$parsedSource) {
            $$parsedSource["partitions"] = $$createField3_0($$parsedSource["partitions"]);
        }
        return new TopicSummary($$parsedSource as Partial<TopicSummary>);
    }
}

// Private type creation functions
const $$createType0 = PartitionFlowNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BrokerFlowNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = StressTestMetrics.createFrom;
const $$createType5 = ConsumerBenchmarkMetrics.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = ConsumerGroupMember.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = PartitionInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = TopicConfigEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
