// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionConfig {
    "id": string;
    "name": string;
    "brokers": string[] | null;

    /**
     * "none", "plain", "scram-sha-256", "scram-sha-512", "ssl", "mtls", "oauthbearer"
     */
    "authType": string;
    "username": string;
    "password": string;
    "tlsEnabled": boolean;
    "caCertPath": string;
    "clientCertPath": string;
    "clientKeyPath": string;
    "insecureSkipVerify": boolean;
    "token": string;
    "schemaRegistryUrl": string;
    "schemaRegistryUser": string;
    "schemaRegistryPass": string;
}

export interface ConnectionStatus {
    "connected": boolean;
    "clusterId": string;
    "controllerId": number;
    "brokers": string[] | null;
    "topicsCount": number;
    "latencyMs": number;
    "error"?: string;
}

export interface ConsumerBenchmarkConfig {
    "topic": string;
    "groupId": string;

    /**
     * "drop", "store", "inspect"
     */
    "mode": string;
    "storeFilePath": string;

    /**
     * "raw", "jsonl", "csv_hex", "pcap_like"
     */
    "storeFormat": string;

    /**
     * "latest", "earliest"
     */
    "autoOffsetReset": string;
    "kaitaiFormatId"?: string;
}

export interface ConsumerBenchmarkMetrics {
    "active": boolean;
    "topic": string;
    "mode": string;
    "elapsedSeconds": number;
    "consumedMessages": number;
    "consumedBytes": number;
    "currentMsgRate": number;
    "currentByteRate": number;
    "droppedMessages": number;
    "storedMessages": number;
    "errorsCount": number;
}

export interface ConsumerGroupInfo {
    "groupId": string;
    "state": string;
    "protocolType": string;
    "protocol": string;
    "members": ConsumerGroupMember[] | null;
    "lagTotal": number;
}

export interface ConsumerGroupMember {
    "memberId": string;
    "clientId": string;
    "clientHost": string;
}

export interface CreateTopicRequest {
    "name": string;
    "partitions": number;
    "replicationFactor": number;

    /**
     * e.g. "retention.ms": "86400000", "cleanup.policy": "delete"
     */
    "configs": { [_ in string]?: string } | null;
}

export interface KafkaRecord {
    "topic": string;
    "partition": number;
    "offset": number;
    "key": string;
    "keyBase64": string;
    "value": string;
    "valueBase64": string;
    "valueHex": string;
    "headers": { [_ in string]?: string } | null;
    "timestamp": string;

    /**
     * "json", "binary", "text", "avro", "protobuf"
     */
    "format": string;

    /**
     * Populated if parsed via Kaitai or Schema Registry
     */
    "parsedJson": string;
}

export interface KaitaiFormat {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "extension": string;
    "ksySrc": string;
    "compiled": boolean;
    "binaryPath": string;
    "lastBuilt": string;
    "structName": string;
    "checksum": string;
    "buildError"?: string;
}

export interface ParseRequest {
    "formatId": string;
    "dataBase64": string;
    "dataHex": string;
}

export interface ParseResult {
    "success": boolean;
    "error"?: string;
    "result"?: any;
    "elapsedMs": number;
}

export interface PartitionInfo {
    "id": number;
    "leader": number;
    "replicas": number[] | null;
    "isr": number[] | null;
    "earliestOffset": number;
    "latestOffset": number;
}

export interface ProduceRequest {
    "topic": string;
    "key": string;

    /**
     * "string", "hex", "base64"
     */
    "keyFormat": string;
    "value": string;

    /**
     * "string", "json", "base64", "hex", "binary"
     */
    "valueFormat": string;
    "headers": { [_ in string]?: string } | null;

    /**
     * -1 for auto-hash/round-robin
     */
    "partition": number;
    "kaitaiFormatId"?: string;
}

export interface ProduceResponse {
    "success": boolean;
    "topic": string;
    "partition": number;
    "offset": number;
    "timestamp": string;
    "error"?: string;
}

export interface StressTestConfig {
    "topic": string;

    /**
     * goroutine worker pool count
     */
    "concurrency": number;

    /**
     * messages/second across all workers (0 for unbounded max speed)
     */
    "targetRate": number;

    /**
     * 0 for until stopped
     */
    "durationSeconds": number;

    /**
     * size for random payload
     */
    "messageSizeBytes": number;

    /**
     * "random", "counter", "custom", "kaitai_template"
     */
    "payloadType": string;

    /**
     * Used if payloadType == "custom"
     */
    "customPayload": string;

    /**
     * Used if payloadType == "kaitai_template"
     */
    "kaitaiFormatId": string;

    /**
     * "none", "uuid", "counter", "fixed"
     */
    "keyPattern": string;

    /**
     * "none", "gzip", "snappy", "lz4", "zstd"
     */
    "compression": string;
}

export interface StressTestMetrics {
    "active": boolean;
    "topic": string;
    "elapsedSeconds": number;
    "sentMessages": number;
    "sentBytes": number;
    "currentMsgRate": number;
    "currentByteRate": number;
    "errorsCount": number;
    "lastError"?: string;

    /**
     * ms
     */
    "latencyP50": number;

    /**
     * ms
     */
    "latencyP95": number;

    /**
     * ms
     */
    "latencyP99": number;

    /**
     * ms
     */
    "latencyAvg": number;
}

export interface TailRequest {
    "topic": string;

    /**
     * -1 for all partitions
     */
    "partition": number;

    /**
     * e.g. last 10, 50, 100 messages
     */
    "count": number;
    "kaitaiFormatId"?: string;
}

export interface TopicConfigEntry {
    "name": string;
    "value": string;
    "isDefault": boolean;
    "source": string;
}

export interface TopicDetail {
    "name": string;
    "partitionsCount": number;
    "replicationFactor": number;
    "partitions": PartitionInfo[] | null;
    "configs": TopicConfigEntry[] | null;
}

export interface TopicSummary {
    "name": string;
    "partitionsCount": number;
    "replicationFactor": number;
    "partitions": PartitionInfo[] | null;
}
