// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AlterTopicConfig sets or deletes a topic configuration override
 */
export function AlterTopicConfig(topic: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(297428062, topic, key, value);
}

/**
 * Connect establishes a connection to the Kafka cluster
 */
export function Connect(cfg: models$0.ConnectionConfig): $CancellablePromise<models$0.ConnectionStatus | null> {
    return $Call.ByID(1964317031, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateTopic creates a new topic with partitions, replication factor, and optional configs
 */
export function CreateTopic(req: models$0.CreateTopicRequest): $CancellablePromise<void> {
    return $Call.ByID(1962472350, req);
}

/**
 * DeleteTopic deletes a topic from the cluster
 */
export function DeleteTopic(name: string): $CancellablePromise<void> {
    return $Call.ByID(879443071, name);
}

/**
 * Disconnect terminates the Kafka connection
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2872817913);
}

/**
 * GetClusterFlow returns the real-time topology and data rate flow across Producers, Brokers, Partitions, and Consumers
 */
export function GetClusterFlow(topic: string): $CancellablePromise<models$0.ClusterFlowData | null> {
    return $Call.ByID(3646218229, topic).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConsumerMetrics returns consumer throughput metrics
 */
export function GetConsumerMetrics(): $CancellablePromise<models$0.ConsumerBenchmarkMetrics> {
    return $Call.ByID(2624447970).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetStatus returns the current connection status
 */
export function GetStatus(): $CancellablePromise<models$0.ConnectionStatus> {
    return $Call.ByID(1017657287).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetStressTestMetrics returns real-time stress testing stats
 */
export function GetStressTestMetrics(): $CancellablePromise<models$0.StressTestMetrics> {
    return $Call.ByID(127675038).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTopicDetail retrieves partition metadata and broker topic configurations
 */
export function GetTopicDetail(name: string): $CancellablePromise<models$0.TopicDetail | null> {
    return $Call.ByID(2296065405, name).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListConsumerGroups returns active consumer groups
 */
export function ListConsumerGroups(): $CancellablePromise<models$0.ConsumerGroupInfo[]> {
    return $Call.ByID(3120934291).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListTopics returns summaries of all topics in the cluster
 */
export function ListTopics(): $CancellablePromise<models$0.TopicSummary[]> {
    return $Call.ByID(3938136431).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Produce sends a single record to Kafka
 */
export function Produce(req: models$0.ProduceRequest): $CancellablePromise<models$0.ProduceResponse | null> {
    return $Call.ByID(3712232365, req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * StartConsumer runs a consumer in drop/store/inspect mode
 */
export function StartConsumer(cfg: models$0.ConsumerBenchmarkConfig): $CancellablePromise<void> {
    return $Call.ByID(3257373821, cfg);
}

/**
 * StartStressTest launches a high-throughput producer worker pool
 */
export function StartStressTest(cfg: models$0.StressTestConfig): $CancellablePromise<void> {
    return $Call.ByID(4155522569, cfg);
}

/**
 * StopConsumer halts the active consumer
 */
export function StopConsumer(): $CancellablePromise<void> {
    return $Call.ByID(2655777819);
}

/**
 * StopStressTest terminates an active producer stress test
 */
export function StopStressTest(): $CancellablePromise<void> {
    return $Call.ByID(1529704951);
}

/**
 * TailTopic fetches the last N records from a topic
 */
export function TailTopic(req: models$0.TailRequest): $CancellablePromise<models$0.KafkaRecord[]> {
    return $Call.ByID(1215022080, req).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * TestConnection checks connection without persisting it
 */
export function TestConnection(cfg: models$0.ConnectionConfig): $CancellablePromise<models$0.ConnectionStatus | null> {
    return $Call.ByID(1978054687, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.ConnectionStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ClusterFlowData.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.ConsumerBenchmarkMetrics.createFrom;
const $$createType5 = models$0.StressTestMetrics.createFrom;
const $$createType6 = models$0.TopicDetail.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = models$0.ConsumerGroupInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.TopicSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.ProduceResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = models$0.KafkaRecord.createFrom;
const $$createType15 = $Create.Array($$createType14);
