// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AlterTopicConfig sets or deletes a topic configuration override
 */
export function AlterTopicConfig(topic: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(297428062, topic, key, value);
}

/**
 * Connect establishes a connection to the Kafka cluster
 */
export function Connect(cfg: models$0.ConnectionConfig): $CancellablePromise<models$0.ConnectionStatus | null> {
    return $Call.ByID(1964317031, cfg);
}

/**
 * CreateTopic creates a new topic with partitions, replication factor, and optional configs
 */
export function CreateTopic(req: models$0.CreateTopicRequest): $CancellablePromise<void> {
    return $Call.ByID(1962472350, req);
}

/**
 * DeleteTopic deletes a topic from the cluster
 */
export function DeleteTopic(name: string): $CancellablePromise<void> {
    return $Call.ByID(879443071, name);
}

/**
 * Disconnect terminates the Kafka connection
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2872817913);
}

/**
 * GetConsumerMetrics returns consumer throughput metrics
 */
export function GetConsumerMetrics(): $CancellablePromise<models$0.ConsumerBenchmarkMetrics> {
    return $Call.ByID(2624447970);
}

/**
 * GetStatus returns the current connection status
 */
export function GetStatus(): $CancellablePromise<models$0.ConnectionStatus> {
    return $Call.ByID(1017657287);
}

/**
 * GetStressTestMetrics returns real-time stress testing stats
 */
export function GetStressTestMetrics(): $CancellablePromise<models$0.StressTestMetrics> {
    return $Call.ByID(127675038);
}

/**
 * GetTopicDetail retrieves partition metadata and broker topic configurations
 */
export function GetTopicDetail(name: string): $CancellablePromise<models$0.TopicDetail | null> {
    return $Call.ByID(2296065405, name);
}

/**
 * ListConsumerGroups returns active consumer groups
 */
export function ListConsumerGroups(): $CancellablePromise<models$0.ConsumerGroupInfo[] | null> {
    return $Call.ByID(3120934291);
}

/**
 * ListTopics returns summaries of all topics in the cluster
 */
export function ListTopics(): $CancellablePromise<models$0.TopicSummary[] | null> {
    return $Call.ByID(3938136431);
}

/**
 * Produce sends a single record to Kafka
 */
export function Produce(req: models$0.ProduceRequest): $CancellablePromise<models$0.ProduceResponse | null> {
    return $Call.ByID(3712232365, req);
}

/**
 * StartConsumer runs a consumer in drop/store/inspect mode
 */
export function StartConsumer(cfg: models$0.ConsumerBenchmarkConfig): $CancellablePromise<void> {
    return $Call.ByID(3257373821, cfg);
}

/**
 * StartStressTest launches a high-throughput producer worker pool
 */
export function StartStressTest(cfg: models$0.StressTestConfig): $CancellablePromise<void> {
    return $Call.ByID(4155522569, cfg);
}

/**
 * StopConsumer halts the active consumer
 */
export function StopConsumer(): $CancellablePromise<void> {
    return $Call.ByID(2655777819);
}

/**
 * StopStressTest terminates an active producer stress test
 */
export function StopStressTest(): $CancellablePromise<void> {
    return $Call.ByID(1529704951);
}

/**
 * TailTopic fetches the last N records from a topic
 */
export function TailTopic(req: models$0.TailRequest): $CancellablePromise<models$0.KafkaRecord[] | null> {
    return $Call.ByID(1215022080, req);
}

/**
 * TestConnection checks connection without persisting it
 */
export function TestConnection(cfg: models$0.ConnectionConfig): $CancellablePromise<models$0.ConnectionStatus | null> {
    return $Call.ByID(1978054687, cfg);
}
