// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SystemTelemetry {
    "timestamp": string;
    "goroutines": number;
    "allocMb": number;
    "totalAllocMb": number;
    "sysMb": number;
    "numGc": number;
    "numCpu": number;
}
