// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SystemTelemetry {
    "timestamp": string;
    "goroutines": number;
    "allocMb": number;
    "totalAllocMb": number;
    "sysMb": number;
    "numGc": number;
    "numCpu": number;

    /** Creates a new SystemTelemetry instance. */
    constructor($$source: Partial<SystemTelemetry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("goroutines" in $$source)) {
            this["goroutines"] = 0;
        }
        if (!("allocMb" in $$source)) {
            this["allocMb"] = 0;
        }
        if (!("totalAllocMb" in $$source)) {
            this["totalAllocMb"] = 0;
        }
        if (!("sysMb" in $$source)) {
            this["sysMb"] = 0;
        }
        if (!("numGc" in $$source)) {
            this["numGc"] = 0;
        }
        if (!("numCpu" in $$source)) {
            this["numCpu"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemTelemetry instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemTelemetry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemTelemetry($$parsedSource as Partial<SystemTelemetry>);
    }
}
