// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Configure(url: string, user: string, pass: string): $CancellablePromise<void> {
    return $Call.ByID(2054752107, url, user, pass);
}

export function GetSchema(subject: string, version: number): $CancellablePromise<string> {
    return $Call.ByID(3042934488, subject, version);
}

export function ListSubjects(): $CancellablePromise<string[]> {
    return $Call.ByID(3506808344).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
